# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'searchmovies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for searchmovies
  pod 'RealmSwift'
  pod 'Moya' 
  pod 'Moya-ModelMapper/RxSwift', '6.0.0-beta.1'
  pod 'SDWebImage', '~> 4.0'

  target 'searchmoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'searchmoviesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
